In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({'col1':[0,1,2,1], 'col2':['book','pen','book','box']})
df

col1  col2
0     0  book
1     1   pen
2     2  book
3     1   box

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   col1    4 non-null      int64 
 1   col2    4 non-null      object
dtypes: int64(1), object(1)
memory usage: 192.0+ bytes


In [4]:
pd.get_dummies(df)   # str만 원핫으로 바꿔줌 

col1  col2_book  col2_box  col2_pen
0     0          1         0         0
1     1          0         0         1
2     2          1         0         0
3     1          0         1         0

In [5]:
df['col1'] = df['col1'].astype(str)  # col1 의 데이터 타입을 string 타입으로 바꿈 

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   col1    4 non-null      object
 1   col2    4 non-null      object
dtypes: object(2)
memory usage: 192.0+ bytes


In [7]:
pd.get_dummies(df)  # int, float -> 안바꿈, str -> 바꿈 

col1_0  col1_1  col1_2  col2_book  col2_box  col2_pen
0       1       0       0          1         0         0
1       0       1       0          0         0         1
2       0       0       1          1         0         0
3       0       1       0          0         1         0

In [8]:
### scikit-learn  onehot 함수 
from sklearn.preprocessing import OneHotEncoder

In [9]:
one = OneHotEncoder(sparse=False)
new =one.fit_transform(df)

In [20]:
one.get_feature_names()

array(['x0_0', 'x0_1', 'x0_2', 'x1_book', 'x1_box', 'x1_pen'],
      dtype=object)

In [10]:
new

array([[1., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 1.],
       [0., 0., 1., 1., 0., 0.],
       [0., 1., 0., 0., 1., 0.]])

In [14]:
df

col1  col2
0    0  book
1    1   pen
2    2  book
3    1   box

In [18]:
### 새로운 데이터? 
import numpy as np
one.transform(np.array([[0, 'book']]))

array([[1., 0., 0., 1., 0., 0.]])

In [23]:
### Keras (전처리 가공후에 사용하시길 권장 )
from keras.utils import to_categorical

to_categorical(df)   #'book' 

ValueError: invalid literal for int() with base 10: 'book'

In [26]:
from sklearn.preprocessing import LabelEncoder    # string 열의 값 -> 숫자로

lb = LabelEncoder()
result =lb.fit_transform(df.col2)
result

array([0, 2, 0, 1])

In [29]:
one.inverse_transform([[1., 0., 0., 1., 0., 0.]])    # onehot -> 원데이터 

array([['0', 'book']], dtype=object)